# アクション名
name: CI

# タイミングを指定
on:
  pull_request:
    branches: ["main"]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_YUMEMI_API_KEY: ${{ secrets.YUMEMI_API_KEY }}
          directory: ./
          file_name: .env
          fail_on_empty: false
          sort_keys: false

  build:
    name: build
    runs-on: ubuntu-latest
    needs: create-envfile
    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "./**/*.{js,mjs,cjs,ts,jsx,tsx}"
      - name: Run eslint
        run: yarn lint
      - name: Run Jest
        run: yarn jest
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Show coverage in comments
        uses: MishaKav/jest-coverage-comment@main
